---
title: "Affordable Housing"
author: "Zhuohan"
date: "5/27/2021"
output: pdf_document
---

```{r }

rentdata <- read.csv("medianAskingRent_All.csv")

discountdata <- read.csv("discountShare_All.csv")

manhattan <- rentdata[rentdata$Borough=='Manhattan', ]

sum(manhattan[,'X2010.01'], na.rm = TRUE)
ls(rentdata)[4:139]
#To calculate manhattan sum col for every year
sumcol_M <- 0
for(i in ls(rentdata)[4:139]){
  sumcol_M[i] = sum(manhattan[,i], na.rm = TRUE)
}


sumcol_Q <- NULL
#for(j in unique(rentdata$Borough)){
for(i in ls(rentdata)[4:139]){
  sumcol_Q[i] = sum(rentdata[rentdata$Borough=='Queens', i], na.rm = TRUE)
}

library(ggplot2)
ggplot(data = rentdata, aes(rentdata[,-(1:3)]))+geom_histogram()
hist(rentdata[,-(1:3)])
       


sumcol <- function(x){
  sum(x)
}
SUMS <- apply(manhattan[,ls(rentdata)[4:139]], MARGIN = 2, FUN = sumcol)
SUMS

newdata <- rentdata[rentdata$Borough==c('Queens', 'Brooklyn', 'Bronx', 'Staten Island'),]

library(ggplot2)
ggplot(data = newdata)+
  geom_point(mapping = aes(x = c(1:136), y = ))


library(magrittr)
library(dplyr)
#borough = Brooklyn
Brooklyndata <- newdata %>%
  filter(areaType=='neighborhood')%>%
  filter(Borough=="Brooklyn")
as.matrix(apply(Brooklyndata[4:139],2,which.max))
table(as.matrix(apply(Brooklyndata[4:139],2,which.max))[,1])
Brooklyndata[5, ]

unique(newdata$Borough)
#borough = Bronx
Bronxdata <- newdata %>%
  filter(areaType=='neighborhood')%>%
  filter(Borough=="Bronx")
as.matrix(apply(Bronxdata[4:139],2,which.min))
Bronxdata[4,]
#borough = 'Queens'
Queensdata <- newdata %>%
  filter(areaType=='neighborhood')%>%
  filter(Borough=="Queens")
as.matrix(apply(Queensdata[4:139],2,which.max))
table(as.matrix(apply(Queensdata[4:139],2,which.max))[,1])
Queensdata[1,]
Queensdata[5,]
```


#to find the lowest density neghborhood from 2006 to 2019
```{r }

lowpop <- read.csv("sub-borougharea-populationdensity1000personspersquaremile.csv")

subgroup <- lowpop[4:17]
as.matrix(apply(lowpop[4:17],2,which.min))
subsub <- subgroup[-54,]
as.matrix(apply(subsub, 2, which.min))
lowpop[55,]

newdataset <- lowpop[,c(1:3,17)]
new1 <- newdataset[order(newdataset$X2019),]
which(newdataset$X2019 %in% median(new1$X2019))
```

#To find median density neighborhoods
```{r}
library(magrittr)
library(dplyr)
#borough = brooklyn
densitydata <- read.csv("sub-borougharea-populationdensity1000personspersquaremile.csv")
Brooklyndata <- densitydata %>%
  filter(borough=='Brooklyn')
sort(Brooklyndata$X2019)

which(Brooklyndata$X2019 %in% 42.84488)

#borough = Queens
densitydata <- read.csv("sub-borougharea-populationdensity1000personspersquaremile.csv")
Queensdata <- densitydata %>%
  filter(borough=='Queens')
sort(Queensdata$X2019)

#borough = bronx
densitydata <- read.csv("sub-borougharea-populationdensity1000personspersquaremile.csv")
Bronxdata <- densitydata %>%
  filter(borough=='Bronx')
sort(Bronxdata$X2019)

#borough = Manhattan 
densitydata <- read.csv("sub-borougharea-populationdensity1000personspersquaremile.csv")
Manhattandata <- densitydata %>%
  filter(borough=='Manhattan')
sort(Manhattandata$X2019)
Manhattandata[,Manhattandata$X2019==60.64754]


#borough = Staten Island 
densitydata <- read.csv("sub-borougharea-populationdensity1000personspersquaremile.csv")
StatenIslanddata <- densitydata %>%
  filter(borough=='StatenIsland')
sort(StatenIslanddata$X2019)
Manhattandata[,Manhattandata$X2019==60.64754]

```


#housing model
```{r }
rawhousing <- read.csv("EXPORT_housing.csv")
head(rawhousing)
summary(rawhousing)
housingdata1 <- rawhousing[rawhousing$costestimate!= '$0.00',]
housingdata <- housingdata1%>%
  filter(occ_proposed == 'Residential: 1-2 Family Houses (J-3)')
str(housingdata)
#to chech NaN, NA, Inf
#any(is.infinite(housingdata$costestimate))
#delete $ sign in cost estimate
housingdata$costestimate <- as.numeric(gsub("\\$", "", housingdata$costestimate))
#run a linear regression model
lmcost <- lm(housingdata$costestimate~ housingdata$schoolcommnty+housingdata$policeprecnct+housingdata$firedivision+1)

summary(lmcost)

```

#Select demogrpahic information(income levels) from NTA datasets
```{r}
NTA <- read.csv("NTA.csv")
head(NTA)
Bronxdata <- NTA %>%
  filter(BoroName=='Bronx')%>%
  filter(NTAName=='Parkchester' | NTAName =='Soundview-Bruckner'|NTAName=='Soundview-Castle Hill-Clason Point-Harding Park')%>%
  select("NTAName","mdfamincE","famiu10E","fami10t14E","fami15t24E","fami25t34E","fami35t49E","fami50t74E","fami75t99E","fi100t149E","fi150t199E","fami200plE","fampvuE","fambwpvE")

```

#Visulization 
```{r}
library(ggplot2)
brooklyn <- read.csv("NTA BROOKLYN DATA .csv", check.names = FALSE)

brooklyn <- brooklyn[1,]
as.character(names(brooklyn))[4]
brooklyn_new <- data.frame(lev =  c("Family income of less than $10,000","$10,000 to $14,999", "$15,000 to $24,999", "$25,000 to $34,999", "$35,000 to $49,999", "$50,000 to $74,999", "$75,000 to $99,999", "$100,000 to $149,999", "$150,000 to $199,999", "$200,000 or more"), num1 = as.numeric(manh))
ggplot(brooklyn_new, mapping = aes(x = factor(lev, levels = c("Family income of less than $10,000","$10,000 to $14,999", "$15,000 to $24,999", "$25,000 to $34,999", "$35,000 to $49,999", "$50,000 to $74,999", "$75,000 to $99,999", "$100,000 to $149,999", "$150,000 to $199,999", "$200,000 or more")), y = num1)) + 
  geom_col(size = 1, color = "darkblue", fill = "white") +
   labs(title = "Income Distribution", x="Income ranges", y = "Number of families")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  geom_line(size = 1.5, color="red", group = 1) + 
  scale_y_continuous(sec.axis = sec_axis(~., name = "number"))
  
 
```


```{r}
partD_2 <- data.frame(lev = c("Family income of less than $10,000","$10,000 to $14,999", "$15,000 to $24,999", "$25,000 to $34,999", "$35,000 to $49,999", "$50,000 to $74,999", "$75,000 to $99,999", "$100,000 to $149,999", "$150,000 to $199,999", "$200,000 or more"), num = brooklyn_new$num1)

ggplot(partD_2, mapping = aes(x = factor(lev, levels = c("Family income of less than $10,000","$10,000 to $14,999", "$15,000 to $24,999", "$25,000 to $34,999", "$35,000 to $49,999", "$50,000 to $74,999", "$75,000 to $99,999", "$100,000 to $149,999", "$150,000 to $199,999", "$200,000 or more")), y = num))+
  geom_col(size = 1, color = "darkblue", fill = "white")+
  geom_line(color = "red", group = 1, size = 1.5)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  labs(title = "Number of apartments correspond to each income level (60% benchmark)", x = "Households' income levels", y = "Number of apartments")


ggplot(partD_2, mapping = aes(x = factor(lev, levels = c("Family income of less than $10,000","$10,000 to $14,999", "$15,000 to $24,999", "$25,000 to $34,999", "$35,000 to $49,999", "$50,000 to $74,999", "$75,000 to $99,999", "$100,000 to $149,999", "$150,000 to $199,999", "$200,000 or more")), y = num1)) + 
  geom_col(size = 1, color = "darkblue", fill = "white") +
   labs(title = "Income Distribution", x="Income ranges", y = "Number of families")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  geom_line(size = 1.5, color="red", group = 1) + 
  scale_y_continuous(sec.axis = sec_axis(~., name = "number"))






d = c("$10,000 and less","$10,000 to $14,999", "$15,000 to $24,999", "$25,000 to $34,999", "$35,000 to $49,999", "$50,000 to $74,999", "$75,000 to $99,999", "$100,000 to $149,999", "$150,000 to $199,999", "$200,000 or more")
ggplot(brooklyn_new, mapping = aes(x = factor(lev, levels = d), y = num1)) + 
  geom_col(size = 1, color = "darkblue", fill = "white") +
   labs(title = "Income Distribution", x="Income ranges", y = "Number of families")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  geom_line(size = 1.5, color="red", group = 1) + 
  scale_y_continuous(sec.axis = sec_axis(~., name = "number"))


factor(brooklyn_new$lev, levels = d)

factor(partD_2$lev, levels = c("Family income of less than $10,000","$10,000 to $14,999", "$15,000 to $24,999", "$25,000 to $34,999", "$35,000 to $49,999", "$50,000 to $74,999", "$75,000 to $99,999", "$100,000 to $149,999", "$150,000 to $199,999", "$200,000 or more"))
```


```{r}
setwd("/Users/zhuohan/Desktop/Wegne Lee/Wayne")
si <- read.csv("StatenIsland_demographics.csv")
si <- si[3,]
si <- si[,c(3:12)]

si_new <- data.frame(level = names(brooklyn)[c(3:10, 12,13)], number = as.numeric(si))
ggplot(si_new) + 
  geom_col(aes(x = factor(level,levels = c("Family income of less than $10,000","$10,000 to $14,999", "$15,000 to $24,999", "$25,000 to $34,999", "$35,000 to $49,999", "$50,000 to $74,999", "$75,000 to $99,999", "$100,000 to $149,999", "$150,000 to $199,999", "$200,000 or more")), y = number), size = 1, color = "darkblue", fill = "white") +
  geom_line(aes(x = level, y = number), size = 1.5, color="red", group = 1) + 
  scale_y_continuous(sec.axis = sec_axis(~., name = "number"))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  labs(title = "Income Distribution", x="Income ranges", y = "Number of families")



manh <- read.csv("manhattan_demographics.csv",check.names = FALSE)
manh <- manh[1,4:13]
manh_new <- data.frame(level = names(brooklyn)[c(3:10, 12,13)], number = as.numeric(manh))
ggplot(manh_new) + 
  geom_col(aes(x = factor(level, levels = c("Family income of less than $10,000","$10,000 to $14,999", "$15,000 to $24,999", "$25,000 to $34,999", "$35,000 to $49,999", "$50,000 to $74,999", "$75,000 to $99,999", "$100,000 to $149,999", "$150,000 to $199,999", "$200,000 or more")), y = number), size = 1, color = "darkblue", fill = "white") +
  geom_line(aes(x = level, y = number), size = 1.5, color="red", group = 1) + 
  scale_y_continuous(sec.axis = sec_axis(~., name = "number"))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  labs(title = "Income Distribution", x="Income ranges", y = "Number of families")

queen_new <- data.frame(level = names(brooklyn)[c(3:10, 12,13)], number = c(1926, 1473, 2604, 1571, 2370, 3411, 1915, 1751, 578, 410))
ggplot(queen_new) + 
  geom_col(aes(x = level, y = number), size = 1, color = "darkblue", fill = "white") +
  geom_line(aes(x = level, y = number), size = 1.5, color="red", group = 1) + 
  scale_y_continuous(sec.axis = sec_axis(~., name = "number"))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  labs(title = "Income Distribution", x="Income ranges", y = "Number of families")



```


```{r}

zillow <- read.csv("zillow_rents_week4.csv", check.names = FALSE)
sum(zillow[zillow$Neighborhood==c("Soundview","Parkchester"),]$Price)

nrow(zillow[zillow$Neighborhood==c("Soundview","Parkchester"),])

Park <- data.frame(week = 1:4, Mean_price = c(1932,2093,2027,2133))
ggplot(Park)%>%
  geom_line( mapping = aes(x = week, y = Mean_price), size = 1.5)

plot(Park$week, Park$Mean_price,  main = "Distribution of Apartment Prices over Past Four Weeks", xlab = "Week", ylab = "Mean Rent Price" , ylim = c(1300, 3500))+
lines(Park$week, Park$Mean_price)+
abline(h = 1407.93, col = "red", lty = 1)+
  text(3, 1500, "30% bechmark", col = "red")+
abline(h = 2231.89, col = "darkgoldenrod1", lty = 2)+
  text(3, 2350, "45% benchmark", col= "darkgoldenrod1")+
abline(h = 2975.85, col = "blue", lty = 3)+
  text(3, 3100, "60% benchmark", col = "blue")


```